#!/bin/sh

# Run tests
echo "Running tests..."
make validate-fonts # ensure the font subset supports all localization texts
make test # linter is run as part of the tests build

status=$?
if [ "$status" = 0 ] ; then
    echo "Unit tests ran successfully."
else
    echo "Unit tests failed."
    exit 1
fi