name: Pull request CI checks

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Clean build directory
        run: make clean
      - name: Execute build
        run: make build

  lint:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Update CocoaPods Specs
        run: pod repo update
      - name: Swift Lint
        run: swiftlint
      - name: Pod Lint for VirtusizeCore
        run: pod lib lint VirtusizeCore.podspec --allow-warnings
      - name: Pod Lint for Virtusize
        uses: nick-invision/retry@v2.0.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint Virtusize.podspec --allow-warnings

  test:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run VirtusizeCoreTests
        run: make virtusize-core-test
      - name: Run VirtusizeTests
        run: make virtusize-test