name: Pull request CI checks

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Clean build directory
        run: make clean
      - name: Execute build
        run: make build

  lint:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Update CocoaPods Specs
        run: pod repo update
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint
      - name: Pod Lint for VirtusizeCore
        run: pod lib lint VirtusizeCore.podspec --allow-warnings
      - name: Pod Lint for Virtusize
        uses: nick-fields/retry@v2.9.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_on: error
          command: pod lib lint Virtusize.podspec --allow-warnings

  test:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      # This step should be removed after 6 Jan, 2025 when macos-latest updates XCode from 16.0 to 16.2
      - name: Latest XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Run VirtusizeCoreTests
        run: make virtusize-core-test
      - name: Run VirtusizeTests
        run: make virtusize-test
