name: Release

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Cocoapods
      run: gem install cocoapods

    - name: Pod validation
      run: |
        set -e -o pipefail
        pod lib lint --allow-warnings
        pod spec lint --allow-warnings

    - name: Push to CocoaPods
      run: |
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
