name: Release

on:
  release:
    types: [released]

env:
  COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Pod Validation for VirtusizeCore
        run: |
          set -e -o pipefail
          pod lib lint VirtusizeCore.podspec --allow-warnings
          pod spec lint VirtusizeCore.podspec --allow-warnings

      - name: Push VirtusizeCore to CocoaPods
        run: |
          pod trunk push VirtusizeCore.podspec --allow-warnings
          pod repo update

      - name: Pod Validation for VirtusizeAuth
        run: |
          set -e -o pipefail
          pod lib lint VirtusizeAuth.podspec --allow-warnings
          pod spec lint VirtusizeAuth.podspec --allow-warnings

      - name: Push VirtusizeAuth to CocoaPods
        run: |
          pod trunk push VirtusizeAuth.podspec --allow-warnings
          pod repo update

      - name: Pod Validation for Virtusize
        run: |
          set -e -o pipefail
          pod lib lint Virtusize.podspec --allow-warnings
          pod spec lint Virtusize.podspec --allow-warnings

      - name: Push Virtusize to CocoaPods
        run: |
          pod trunk push Virtusize.podspec --allow-warnings
          pod repo update
