name: Release

on:
  release:
    types: [released]

env:
  COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Validate All Pods Locally
        run: |
          set -e -o pipefail
          pod lib lint --include-podspecs="Virtusize*.podspec" --allow-warnings

      # `pod trunk push` automatically validates pod version compatability
      # so there is no need for extra `pod spec lint` call
      # see https://guides.cocoapods.org/making/getting-setup-with-trunk#deploying-a-library
      - name: Push VirtusizeCore to CocoaPods
        run: |
          pod trunk push VirtusizeCore.podspec --allow-warnings --synchronous

      # --synchronous flag ensure the local repo is updated to lint and verify dependant packages
      - name: Push VirtusizeAuth to CocoaPods
        run: |
          pod trunk push VirtusizeAuth.podspec --allow-warnings --synchronous

      - name: Push Virtusize to CocoaPods
        run: |
          pod trunk push Virtusize.podspec --allow-warnings --synchronous
